### ISSUE TITLE
Enable PEM files with CRLF line endings to be used

### ISSUE THREAD

**Issue by stephaneberle9** [libp2p/go-openssl#10]
I was trying to run _go-openssl_ under Windows and got in trouble with the server certificate and private key files to be loaded by the `openssl.ListenAndServeTLS()` function. Instead of starting up normally, the server process ended immediately with the following error: `No PEM certificate found in 'server.crt'`. At the end, it turned out that the only problem were the **CRLF** line endings in the server certificate and private key files. After having changed then to **LF**, everything worked like a charm.

Nevertheless, this is a non-obvious pitfall making _go-openssl_ somewhat difficult to use under Windows. It therefore would be preferable to make it happen that PEM files used regardless whether their line ending is LF or CRLF. This seems also to be a [common practice ](https://crypto.stackexchange.com/a/44125) for most other TLS/SSL applications and libraries.

**Comment by aschmahmann** [comment]
@stephaneberle9 merged your PR, but the regex that allows for arbitrary space and hyphens seems non-spec compliant #12 which we'll try and fix up before doing a release.
